global:
  security:
    allowInsecureImages: true # for custom postgres image

# Part 1: the configuration of Postgres, Minio and LakeFS
postgresql:
  image:
    repository: texera/postgres17-pgroonga
    tag: latest
    debug: true
  auth:
    postgresPassword: root_password  # for executing init script with superuser
  primary:
    resources:
      requests:
        cpu: "4"
        memory: "4Gi"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: local-path # change to specific storageClass if needed.

    initdb:
      scriptsConfigMap: texera-postgresql-init-script

minio:
  mode: standalone
  ingress:
    enabled: false
    hostname: "localhost"
    tls: false
    annotations:
      cert-manager.io/issuer: ""
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "" # replace it with texera hostname
      nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, OPTIONS"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/cors-expose-headers: "ETag, x-amz-meta-custom-header"
      nginx.ingress.kubernetes.io/cors-max-age: "86400"  # Optional: Increase for better caching
  auth:
    rootUser: texera_minio
    rootPassword: password
  service:
    type: NodePort
    nodePorts:
      api: 31000
  persistence:
    enabled: true
    size: 20Gi
    storageClass: local-path # change to specific storageClass if needed.

lakefs:
  secrets:
    authEncryptSecretKey: random_string_for_lakefs
    databaseConnectionString: postgres://postgres:root_password@texera-postgresql:5432/texera_lakefs?sslmode=disable
  service:
    port: 8000
  lakefsConfig: |
    database:
      type: postgres
    blockstore:
      type: s3
      s3:
        endpoint: http://texera-minio:9000
        pre_signed_expiry: 15m
        pre_signed_endpoint: http://localhost:31000
        force_path_style: true
        credentials:
          access_key_id: texera_minio
          secret_access_key: password

webserver:
  name: webserver
  numOfPods: 1  # Number of pods for the Texera deployment
  imageName: texera/texera-web-application:latest # image name of the texera
  service:
    type: NodePort # for testing purpose, NodePort mode is fine
    port: 8080 # port of the pod
    nodePort: 30081 # exposed port

workflowComputingUnitManager:
  name: workflow-computing-unit-manager
  numOfPods: 1
  serviceAccountName: workflow-computing-unit-manager-service-account
  imageName: texera/workflow-computing-unit-managing-service:latest
  service:
    type: NodePort # for testing purpose, NodePort mode is fine
    port: 8888 # port of the pod
    nodePort: 30082 # exposed port

workflowCompilingService:
  name: workflow-compiling-service
  numOfPods: 1
  imageName: texera/workflow-compiling-service:latest
  service:
    type: NodePort
    port: 9090
    nodePort: 30083

fileService:
  name: file-service
  numOfPods: 1
  imageName: texera/file-service:latest
  service:
    type: NodePort
    port: 9092
    nodePort: 30084

# Config required for envoy and workflow pods
envoy:
  replicas: 1
  image:
    repository: envoyproxy/envoy
    tag: v1.31-latest
  port:
    10000
  debug: false
  service:
    type: NodePort
    port: 10000
    nodePort: 31002

# headless service
# each pod's url is: computing-unit-%cuid.workflow-computing-unit.workflow-computing-unit-pool.svc.cluster.local
workflowComputingUnitPool:
  createNamespaces: true
  name: workflow-computing-unit
  namespace: workflow-computing-unit-pool
  imageName: texera/computing-unit-master:latest
  service:
    port: 8085
    targetPort: 8085

texeraEnvVars:
  - name: STORAGE_S3_ENDPOINT
    value: http://texera-minio:9000
  - name: STORAGE_LAKEFS_ENDPOINT
    value: http://texera-lakefs:8000/api/v1
  - name: STORAGE_JDBC_URL
    value: jdbc:postgresql://texera-postgresql:5432/texera_db?currentSchema=texera_db,public
  - name: STORAGE_JDBC_USERNAME
    value: postgres
  - name: STORAGE_JDBC_PASSWORD
    value: root_password
  - name: FILE_SERVICE_GET_PRESIGNED_URL_ENDPOINT
    value: http://texera-file-service:9092/api/dataset/presign-download
  - name: FILE_SERVICE_UPLOAD_ONE_FILE_TO_DATASET_ENDPOINT
    value: http://texera-file-service:9092/api/dataset/did/upload
  - name: USER_SYS_ENABLED
    value: "true"
  - name: STORAGE_ICEBERG_CATALOG_TYPE
    value: postgres
  - name: STORAGE_ICEBERG_CATALOG_POSTGRES_URI_WITHOUT_SCHEME
    value: texera-postgresql:5432/texera_iceberg_catalog
  - name: STORAGE_ICEBERG_CATALOG_POSTGRES_USERNAME
    value: postgres
  - name: STORAGE_ICEBERG_CATALOG_POSTGRES_PASSWORD
    value: root_password
  - name: STORAGE_LAKEFS_AUTH_API_SECRET
    value: random_string_for_lakefs
  - name: STORAGE_LAKEFS_AUTH_USERNAME
    value: AKIAIOSFOLKFSSAMPLES
  - name: STORAGE_LAKEFS_AUTH_PASSWORD
    value: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# Ingress dependency configs
ingress-nginx:
  enabled: true # set to true if k8s does not have nginx installed.
  controller:
    replicaCount: 1
    service:
      type: NodePort
      nodePorts:
        http: 30080
    ingressClassResource:
      name: nginx
      enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  rbac:
    create: true


yWebsocketServer:
  name: y-websocket-server
  replicaCount: 1
  image: jxzliu/y-websocket-server:latest


pythonLanguageServer:
  name: python-language-server
  replicaCount: 8
  image: jxzliu/pylsp:latest
  imagePullSecret: regcred
  resources:
    limits:
      cpu: "1"
      memory: "200Mi"

# Custom Ingress resource configs
ingressPaths:
  enabled: true
  hostname: "localhost"
  # Optional TLS secret (manually created)
  tlsSecretName: ""  # e.g., "texera-tls"
  # Optional Issuer name for cert-manager
  issuer: ""  # e.g., "letsencrypt-prod"
  paths:
    - path: /api/computing-unit
      serviceName: workflow-computing-unit-manager-svc
      servicePort: 8888
    - path: /api/compile
      serviceName: workflow-compiling-service-svc
      servicePort: 9090
    - path: /api/dataset
      serviceName: file-service-svc
      servicePort: 9092
    - path: /api/access/dataset
      serviceName: file-service-svc
      servicePort: 9092
    - path: /wsapi/workflow-websocket
      serviceName: envoy-svc
      servicePort: 10000
    - path: /api
      serviceName: webserver-svc
      servicePort: 8080
    - path: /rtc
      serviceName: y-websocket-server-svc
      servicePort: 1234
    - path: /python-language-server
      serviceName: python-language-server-svc
      servicePort: 3000
    - path: /
      serviceName: webserver-svc
      servicePort: 8080
