storage:
  result-storage-mode: iceberg
  mongodb:
    url: "mongodb://localhost:27017"
    database: "texera_storage"
    commit-batch-size: 1000
  iceberg:
    catalog:
      type: hadoop # either hadoop, rest, or postgres
      rest-uri: "" # the uri of the rest catalog, not needed unless using REST catalog
      postgres:
        # do not include scheme in the uri as Python and Java use different schemes
        uri-without-scheme: "localhost:5432/texera_iceberg_catalog"
        username: "texera_iceberg_admin" # replace with actual username
        password: "password" # replace with actual password
    table:
      result-namespace: "operator-port-result"
      console-messages-namespace: "operator-console-messages"
      runtime-statistics-namespace: "workflow-runtime-statistics"
      commit:
        batch-size: 4096 # decide the buffer size of our IcebergTableWriter
        retry:
          # retry configures the OCC parameter for concurrent write operations in Iceberg
          # Docs about Reliability in Iceberg: https://iceberg.apache.org/docs/1.7.1/reliability/
          # Docs about full parameter list and their meaning: https://iceberg.apache.org/docs/1.7.1/configuration/#write-properties
          num-retries: 10
          min-wait-ms: 100   # 0.1s
          max-wait-ms: 10000 # 10s
  # configuration of the LakeFS & S3 for dataset storage
  lakefs:
    endpoint: "http://localhost:8000/api/v1"
    auth:
      api-secret: ""
      username: ""
      password: ""
    block-storage:
      type: "s3"
      bucket-name: "texera-dataset"

  s3:
    endpoint: "http://localhost:9000"
    auth:
      username: ""
      password: ""

  jdbc:
    url: "jdbc:postgresql://localhost:5432/texera_db?currentSchema=texera_db,public"
    username: "postgres"
    password: ""
