# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-language-server-deployment
  namespace: texera
  labels:
    app: python-language-server
spec:
  replicas: 8 
  selector:
    matchLabels:
      app: python-language-server
  template:
    metadata:
      labels:
        app: python-language-server
    spec:
      containers:
      - name: python-language-server
        image: jxzliu/pylsp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: 1
              memory: "200Mi"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: python-language-server-service
  namespace: texera
  labels:
    app: python-language-server
spec:
  selector:
    app: python-language-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
