auth:
  jwt:
    exp-in-days: 30
    # generate the secret again for each deployment using the following:
    # 'openssl rand -hex 16'  or  'xxd -l16 -ps /dev/urandom'
    256-bit-secret: "8a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d"