services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    container_name: minio
    ports:
      - "9000:9000"   # MinIO API (use this in LakeFS config)
      - "9001:9001"   # MinIO Console UI
    environment:
      - MINIO_ROOT_USER=texera_minio
      - MINIO_ROOT_PASSWORD=password
    command: server --console-address ":9001" /data
    profiles:
      - local-lakefs

  lakefs:
    image: treeverse/lakefs:1.51
    container_name: lakefs
    depends_on:
      - minio
    ports:
      - "8000:8000"  # LakeFS API/UI
    environment:
      # LakeFS metadata store
      - LAKEFS_DATABASE_TYPE=local
      # Authentication
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=random_string_for_lakefs
      # MinIO Storage Configuration for LakeFS
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=http://minio:9000  # MinIO internal service URL
      - LAKEFS_BLOCKSTORE_S3_DISCOVER_BUCKET_REGION=false
      - LAKEFS_BLOCKSTORE_S3_PRE_SIGNED_ENDPOINT=http://localhost:9000
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=texera_minio
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=password
      # LakeFS Installation Credentials
      - LAKEFS_INSTALLATION_USER_NAME=texera-admin
      - LAKEFS_INSTALLATION_ACCESS_KEY_ID=AKIAIOSFOLKFSSAMPLES
      - LAKEFS_INSTALLATION_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    profiles:
      - local-lakefs