---
database:
  type: "postgres"
  postgres:
    connection_string: "postgresql://texera_lakefs_admin:password@localhost:5432/texera_lakefs"

auth:
  encrypt:
    # Replace this with a randomly-generated string. Keep it safe!
    secret_key: "random_string_for_lakefs"

blockstore:
  type: s3
  s3:
    force_path_style: true
    endpoint: http://localhost:9500  # MinIO API now runs on port 9500
    discover_bucket_region: false
    credentials:
      access_key_id: "texera_minio"  # Matches MINIO_ROOT_USER from docker-compose
      secret_access_key: "password"  # Matches MINIO_ROOT_PASSWORD from docker-compose