name: texera-local-test
services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    container_name: texera-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=texera_minio
      - MINIO_ROOT_PASSWORD=password
    command: server --console-address ":9001" /data

  postgres:
    image: groonga/pgroonga:4.0.1-debian-15
    container_name: texera-postgres
    restart: always
    environment:
      - POSTGRES_USER=texera
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "texera", "-d", "texera_db"]
      interval: 10s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./core/scripts/sql:/docker-entrypoint-initdb.d

  lakefs:
    image: treeverse/lakefs:1.51
    container_name: texera-lakefs
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=http://texera-minio:9000
      - LAKEFS_BLOCKSTORE_S3_PRE_SIGNED_ENDPOINT=http://localhost:9000
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=texera_minio
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=password
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=random_string_for_lakefs
      - LAKEFS_LOGGING_LEVEL=INFO
      - LAKEFS_STATS_ENABLED=1
      - LAKEFS_DATABASE_TYPE=postgres
      - LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING=postgres://texera:password@texera-postgres:5432/texera_lakefs?sslmode=disable
      - LAKEFS_INSTALLATION_USER_NAME=texera-admin
      - LAKEFS_INSTALLATION_ACCESS_KEY_ID=AKIAIOSFOLKFSSAMPLES
      - LAKEFS_INSTALLATION_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        lakefs setup --user-name "$LAKEFS_INSTALLATION_USER_NAME" --access-key-id "$LAKEFS_INSTALLATION_ACCESS_KEY_ID" --secret-access-key "$LAKEFS_INSTALLATION_SECRET_ACCESS_KEY" || true
        lakefs run &
        echo "---- lakeFS Web UI ----"
        echo "http://127.0.0.1:8000/"
        echo ""
        echo "Access Key ID    : $LAKEFS_INSTALLATION_ACCESS_KEY_ID"
        echo "Secret Access Key: $LAKEFS_INSTALLATION_SECRET_ACCESS_KEY"
        echo ""
        wait
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/api/v1/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 10

  file-service:
    image: bobbai00/file-service:test
    container_name: texera-file-service
    depends_on:
      minio:
        condition: service_started
      lakefs:
        condition: service_healthy
    environment:
      - STORAGE_S3_ENDPOINT=http://texera-minio:9000
      - STORAGE_LAKEFS_ENDPOINT=http://texera-lakefs:8000/api/v1
    ports:
      - "9092:9092"



volumes:
  postgres_data:

networks:
  default:
    name: texera-local-test