apiVersion: v1
kind: Service
metadata:
  name: envoy-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.envoy.service.type }}
  selector:
    app: envoy
  ports:
    - protocol: TCP
      port: {{ .Values.envoy.service.port }}
      targetPort: {{ .Values.envoy.service.port }}
      # if service type is set to NodePort, include nodePort attribute
      {{- if eq .Values.envoy.service.type "NodePort" }}
      nodePort: {{ .Values.envoy.service.nodePort }}
      {{- end }}