apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lakefs-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: "texera-admin"
  access_key: "AKIAIOSFOLKFSSAMPLES"
  secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
