apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lakefs-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.lakefs.auth.username | quote }}
  access_key: {{ .Values.lakefs.auth.accessKey | quote }}
  secret_key: {{ .Values.lakefs.auth.secretKey | quote }}
