apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgresql-init-script
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  init.sh: |
    #!/bin/bash
    echo "Running Texera schema initialization..."
    export PGPASSWORD=$POSTGRES_PASSWORD
    cat <<'EOF' > /tmp/init.sql
{{ .Files.Get "files/texera_ddl.sql" | indent 6 }}
    EOF
    psql -U postgres -f /tmp/init.sql
    echo "Schema initialization complete."