apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgresql-init-script
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  init.sql: |
{{ .Files.Get "files/texera_ddl.sql" | indent 4 }}