apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-computing-unit-master-prepuller
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-computing-unit-master-prepuller
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-computing-unit-master-prepuller
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-computing-unit-master-prepuller
    spec:
      restartPolicy: Always
      tolerations:
        - operator: "Exists"
      initContainers:
        - name: prepuller
          image: {{ .Values.workflowComputingUnitPool.imageName }}
          imagePullPolicy: Always
          command: ["sh", "-c", "true"]
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:3.2
          resources:
            limits:
              cpu: 1m
              memory: 8Mi
            requests:
              cpu: 1m
              memory: 8Mi 