apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.workflowComputingUnitPool.name }}-svc
  namespace: {{ .Values.workflowComputingUnitPool.namespace }}
spec:
  clusterIP: None
  selector:
    type: computing-unit # TODO: consider change this
  ports:
    - protocol: TCP
      port: {{ .Values.workflowComputingUnitPool.service.port }}
      targetPort: {{ .Values.workflowComputingUnitPool.service.targetPort }}
