server:
  # modify applicationContextPath if you want the root path to be the name of the application
  # for example, set it to /twitter, then the url will become texera.ics.uci.edu:port/twitter
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091
  requestLog:
    type: classic
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: ../log/access.log
        threshold: ALL
        queueSize: 512
        discardingThreshold: 0
        archive: true
        archivedLogFilenamePattern: ../log/access-%d{yyyy-MM-dd}.log.gz
        archivedFileCount: 7
        bufferSize: 8KiB
        immediateFlush: true
logging:
  level: ERROR
  loggers:
    "io.dropwizard": ERROR
  appenders: []