name: GUI Unit Test

on:
  check_suite:
  check_run:
  push:
    branches:
      - 'ci-enable/**'
  pull_request:
    paths:
      - 'core/new-gui/**'
  workflow_dispatch:
jobs:
  gui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Cancel The Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout Texera
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache npm and node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            core/new-gui/node_modules
          key: ${{ runner.os }}-node-with-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-with-modules-
      - name: Install dependency with npm install
        run: npm install --progress=false
        working-directory: core/new-gui
      - name: Backup - Install dependency with npm ci
        if: ${{ failure() }}
        run: npm ci --progress=false
        working-directory: core/new-gui
      - name: Build with npm
        run: npm run build --prod --progress=false
        working-directory: core/new-gui
      - name: Run frontend unit tests
        run: npm run --prefix core/new-gui test:ci
