name: build

on:
  push:
    branches: 
      - 'ci-enable/**'
      - 'master'
  pull_request:
    paths-ignore:
      - 'core/scripts/**'
      - '**/.gitignore'
      - '**.md'
      - '**.csv'
      - '**.txt'
  workflow_dispatch:
  
jobs:
  gui:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 14
        architecture:
          - x64
    steps:
      - name: Checkout Texera
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependency with yarn ci
        run: yarn --cwd core/new-gui install --frozen-lockfile --progress=false
      - name: Build with yarn
        run: yarn --cwd core/new-gui run build
      - name: Run frontend unit tests
        run: yarn --cwd core/new-gui run test:ci

  amber:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs  # add cancel here since this stage is the fastest one.
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout Texera
        uses: actions/checkout@v2
      - name: Lint with scalafmt
        run: cd core/amber && sbt scalafmtCheckAll
      - name: Compile with sbt
        run: cd core/amber && sbt clean compile
      - name: Run backend tests
        run: cd core/amber && sbt -v -J-Xmx2G test
